name: Maestro test infra testing and debugging - Run Cirrus Tasks

on:
  workflow_dispatch:
  
jobs:
  cirrus-sample-task:
    runs-on: macos-15
    steps:
    - run: echo "Maestro test infra testing and debugging - Run Cirrus Tasks"
    - run: pwd