name: Maestro test infra testing and debugging - Run Cirrus Tasks

on:
  pull_request:
  
jobs:
  cirrus-sample-task:
    runs-on: self-hosted
    steps:
    - run: echo "Hello world vishal mac"
    - run: echo $PATH
    - run: ls
    - run: xcodebuild -version
    - run: cirrus --version | echo "cirrus is not installed"
    - run: tart --version | echo "tart is not installed"