name: check node install

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Verify Node
        run: node -v
      - name: Checkout org shared repo
        uses: actions/checkout@v4
        with:
          repository: vishaldesai253/words_backend
          path: words_backend
      - name: current dir
        run: pwd
      - run: ls
      - name: Checkout current
        uses: actions/checkout@v4
      - run: pwd
      - run: ls
