name: Maestro test infra testing and debugging - Run Cirrus Tasks

on:
  pull_request:
  
jobs:
  cirrus-sample-task:
    runs-on: macos-15
    steps:
    - run: echo "Hello world1"
    - run: pwd
    - run: ls
    - run: xcodebuild -version
    - run: cirrus --version | echo "cirrus is not installed"
    - run: tart --version | echo "tart is not installed"