name: Run Cirrus Tasks

on:
  push:
  workflow_dispatch:
  
jobs:
  cirrus:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v2
    - name: Checkout 
      uses: actions/checkout@v4
      with:
        repository: vishaldesai253/words_backend
        ref: main
        path: ../words_backend
    - run: cd ..
    - run: ls
